#
# firebase-oskey-example
# Copyright (c) 2021-2023, OSkey SAS. MIT License.
#

version: '3.9'

# Services
services:
  firebase-oskey-example:
    container_name: firebase-oskey-example
    user: vscode
    build:
      dockerfile: Dockerfile
      context: .
    # ports:
    #   - 19000
    #   - 19001
    #   - 19002
    #   - 19003
    #   - 19004
    #   - 19005
    #   - 19006
    #   - 19007
    volumes:
      - ..:/workspace
      - firebase-oskey-example-devenv-home:/home
    networks:
      - oskey-example-devenv-net

volumes:
  firebase-oskey-example-devenv-home:
    name: firebase-oskey-example-devenv-home
networks:
  oskey-example-devenv-net:
    name: oskey-example-devenv-net
